/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu4b;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author naufal
 */
public class entrigaji extends javax.swing.JFrame {
    int gaji_pokok,tunjangan_kesehatan,kerja,lembur_1,gaji_kotor,gaji_bersih,pajak;
    private Connection conec;

    /**
     * Creates new form entrigaji
     */
    public entrigaji() {
         initComponents();
         koneksidatabase();
         tabel();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        id_pegawai = new javax.swing.JTextField();
        gapok = new javax.swing.JTextField();
        tunjangan = new javax.swing.JTextField();
        gaber = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jabatan = new javax.swing.JComboBox();
        masa_kerja = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        lembur = new javax.swing.JComboBox();
        u_lembur = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pajak_pph = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Entri Gaji Pegawai");

        jLabel2.setText("Id Pegawai");

        jLabel3.setText("Nama ");

        jLabel4.setText("Jabatan");

        jLabel5.setText("Masa Kerja");

        jLabel6.setText("Gaji Pokok");

        jLabel8.setText("Tunjangan ");

        jLabel11.setText("Gaji Bersih");

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cari ID");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Exit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----Pilih----", "Staff", "Manager", "Direktur" }));
        jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanActionPerformed(evt);
            }
        });

        masa_kerja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----Pilih----", "< 1 tahun", ">= 1 tahun", ">= 5 tahun", ">= 10 tahun" }));
        masa_kerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa_kerjaActionPerformed(evt);
            }
        });

        jLabel7.setText("Lembur");

        lembur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----Pilih----", "Tidak Lembur", "1 jam", "2 jam", "3 jam", "4 jam", " " }));
        lembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemburActionPerformed(evt);
            }
        });

        jLabel9.setText("Upah Lembur");

        jLabel10.setText("Pajak");

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id_pegawai", "Nama", "Jabatan", "Masa_kerja", "Lembur", "Gaji_Pokok", "Tunjangan", "Upah_Lembur", "Pajak", "Gaji_bersih"
            }
        ));
        jScrollPane1.setViewportView(tabeldata);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(234, 234, 234))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(418, 418, 418))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pajak_pph, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(gaber, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(u_lembur, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gapok, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(masa_kerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lembur, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(id_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(jButton6))
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)))
                        .addContainerGap(81, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masa_kerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(lembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(gapok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(tunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(u_lembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pajak_pph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(gaber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int x = Integer.parseInt(gapok.getText());
       int y = Integer.parseInt(u_lembur.getText());
       int z = x+y;
    gaji_pokok=Integer.parseInt(gapok.getText());
    tunjangan_kesehatan=Integer.parseInt(tunjangan.getText());
    lembur_1=Integer.parseInt(u_lembur.getText());
    pajak= (int) (0.05*gaji_pokok);
    pajak_pph.setText(Integer.toString(pajak));
       gaber.setText(String.valueOf(z));
       gaji_bersih=gaji_pokok+tunjangan_kesehatan+lembur_1-pajak;
       gaber.setText(Integer.toString(gaji_bersih));
//gaji_pokok=Integer.parseInt(gapok.getText());
//tunjangan_kesehatan=Integer.parseInt(tunkes.getText());

//gaji_kotor=gaji_pokok+tunjangan_kesehatan;
//pajak_pph=(int)(0.05*gaji_kotor);
//gaji_bersih=gaji_kotor/pajak_pph;

//gakor.setText(Integer.toString(gaji_kotor));
//gaber.setText(Integer.toString(gaji_bersih));

//gaji_bersih=kerja*gaji_pokok;


//gaber.setText(Integer.toString(gaji_bersih);


gaji_pokok = Integer.parseInt(gapok.getText());

tunjangan_kesehatan = Integer.parseInt(tunjangan.getText());


        

  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanActionPerformed
      if (jabatan.getSelectedItem().equals("Staff")){
          gapok.setText(""+2000000);
      }   
           if (jabatan.getSelectedItem().equals("Manager")){
           gapok.setText(""+3000000);
           }
           
         if (jabatan.getSelectedItem().equals("Direktur")){
          gapok.setText(""+4000000);  
          
         }
         
    }//GEN-LAST:event_jabatanActionPerformed

    private void masa_kerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa_kerjaActionPerformed
        // TODO add your handling code here:
        if(masa_kerja.getSelectedItem().equals("--PILIH--")){
            tunjangan.setText("");
        }
        if(masa_kerja.getSelectedItem().equals("< 1 tahun")){
            tunjangan.setText("0");
        }
        if(masa_kerja.getSelectedItem().equals(">= 1 tahun")){
            tunjangan.setText(""+100000);
        }
        if(masa_kerja.getSelectedItem().equals(">= 5 tahun")){
            tunjangan.setText(""+300000);
        }
        if(masa_kerja.getSelectedItem().equals(">= 10 tahun")){
            tunjangan.setText(""+500000);
        }
    }//GEN-LAST:event_masa_kerjaActionPerformed

    private void lemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemburActionPerformed
 if(lembur.getSelectedItem().equals("---Pilih---")){
           u_lembur.setText("");  
         }
        else if(lembur.getSelectedItem().equals("Tidak Lembur")){
            u_lembur.setText("0");
        }
        else if(lembur.getSelectedItem().equals("1 jam")){
           u_lembur.setText("50000");
        }
        else if(lembur.getSelectedItem().equals("2 jam")){
            u_lembur.setText("750000");
        }
        else if(lembur.getSelectedItem().equals("3 jam")){
            u_lembur.setText("100000");
        }
        else if(lembur.getSelectedItem().equals("4 jam")){
            u_lembur.setText("125000");
            
        }
    }//GEN-LAST:event_lemburActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String a                    =id_pegawai.getText();
        String b                    =nama.getText();
        String c =   (String)       jabatan.getSelectedItem();
        String d =   (String)       masa_kerja.getSelectedItem();
        String e =   (String)       lembur.getSelectedItem();
        String f                    =gapok.getText();
        String g                    =tunjangan.getText();
        String h                    =u_lembur.getText();
        String i                    =pajak_pph.getText();
        String j                    =gaber.getText();
       
        if(id_pegawai.getText().trim().equals(""))
            JOptionPane.showMessageDialog(null,"Data masih kosong","PERHATIAN!",JOptionPane.WARNING_MESSAGE);
        
        else {
            try {
                java.sql.Statement stat=conec.createStatement();
                ResultSet data=stat.executeQuery("SELECT* FROM tbl_gaji WHERE id_pegawai='"+id_pegawai.getText()+"'");
             String sql="INSERT INTO tbl_gaji VALUES ('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"','"+f+"','"+g+"','"+h+"','"+i+"','"+j+"')";
             stat.executeUpdate(sql);
              id_pegawai.setText("");
              nama.setText("");
              jabatan.setSelectedIndex(0);
              masa_kerja.setSelectedIndex(0);
              lembur.setSelectedIndex(0);
              gapok.setText("");
              tunjangan.setText("");
              u_lembur.setText("");
              pajak_pph.setText("");
              gaber.setText("");
              id_pegawai.requestFocus();
              tabel();
            
              }
            catch (Exception exc) {
                System.err.println("Terjadi Kesalahan:"+exc);
    }  
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String sql=
               "update tbl_gaji set nama='"+nama.getText()+
               "',jabatan='"+jabatan.getSelectedItem()+
               "',Masa_kerja='"+masa_kerja.getSelectedItem()+
               "',Lembur='"+lembur.getSelectedItem()+
               "',pajak='"+pajak_pph.getText()+
               "',gaji_bersih='"+gaber.getText()+
               "'where id_pegawai='"+id_pegawai.getText().trim()+"'";
                if(id_pegawai.getText().trim().equals("")){
               JOptionPane.showMessageDialog(null,"Data Masih Kosong !","Edit Data",JOptionPane.WARNING_MESSAGE);
               id_pegawai.requestFocus();
                }
                else{
                    try{
                        Statement stat=conec.createStatement();
                        stat.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null,"Data Sudah Di Edit","Edit Data",JOptionPane.WARNING_MESSAGE);
                        stat.close();
                        //konek.close();
                        id_pegawai.requestFocus();
                        tabel();
                    }
                   
                    catch(Exception exc){
                        System.err.println("Error:"+exc);
                    }
                
    }                             
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String sql="select*from tbl_gaji WHERE id_pegawai='"+id_pegawai.getText()+"'";
       try {
            Statement stat=conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            if(rs.next()){
                nama.setText(rs.getString("nama"));
                jabatan.setSelectedItem(rs.getString(3));
                masa_kerja.setSelectedItem(rs.getString(4));
                lembur.setSelectedItem(rs.getString(5));
                pajak_pph.setText(rs.getString(9));
                gaber.setText(rs.getString(10));
               
                
            }
            else { JOptionPane.showMessageDialog(null,"Data tidak ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
            id_pegawai.requestFocus();
        }
        stat.close();
       }
    catch(Exception exc) {
            System.err.println("Terjadi Kesalahan:"+exc);
            }
            
                                    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
        String sql="delete from tbl_gaji where id_pegawai='"+id_pegawai.getText().trim()+"'";
        if(id_pegawai.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Null Data, please input data","INFORMASI",JOptionPane.WARNING_MESSAGE);
            id_pegawai.requestFocus();
        }else{
            try{
                Statement stat=conec.createStatement();
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Succes Deleting","INFORMASI",JOptionPane.WARNING_MESSAGE);
                stat.close();
                tabel();
                
                id_pegawai.setText("");
              nama.setText("");
              jabatan.setSelectedIndex(0);
              masa_kerja.setSelectedIndex(0);
              lembur.setSelectedIndex(0);
              gapok.setText("");
              tunjangan.setText("");
              u_lembur.setText("");
              pajak_pph.setText("");
              gaber.setText("");    
                
            }catch(Exception exc) {
                System.err.println(sql);
                System.err.println("Eror : "+exc );
            
        
            }
              
    }                                                                        
            
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       id_pegawai.setText("");
              nama.setText("");
              jabatan.setSelectedIndex(0);
              masa_kerja.setSelectedIndex(0);
              lembur.setSelectedIndex(0);
              gapok.setText("");
              tunjangan.setText("");
              u_lembur.setText("");
              pajak_pph.setText("");
              gaber.setText("");    
              id_pegawai.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entrigaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entrigaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entrigaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entrigaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entrigaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gaber;
    private javax.swing.JTextField gapok;
    private javax.swing.JTextField id_pegawai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jabatan;
    private javax.swing.JComboBox lembur;
    private javax.swing.JComboBox masa_kerja;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField pajak_pph;
    private javax.swing.JTable tabeldata;
    private javax.swing.JTextField tunjangan;
    private javax.swing.JTextField u_lembur;
    // End of variables declaration//GEN-END:variables

    private void koneksidatabase() {
         try{
           Class.forName("com.sql,jdbc.Driver");
       }
       catch(ClassNotFoundException cnf){}
       try{
           conec=
                   DriverManager.getConnection
                   ("jdbc:mysql://localhost/data_pegawai","root","");
           System.out.println("koneksi suskses");
       }
       catch (SQLException se){
           System.out.println("koneksi gagal:" +se);
       }
       catch (Exception e){}
       }

    private void tabel() {
                String sql ="SELECT * FROM tbl_gaji";
        DefaultTableModel a = new DefaultTableModel ();
        a.addColumn("Id_Pegawai");
        a.addColumn("Nama");
        a.addColumn("Jabatan");
        a.addColumn("Masa_kerja");
        a.addColumn("Lembur");
        a.addColumn("Gaji_Pokok");
        a.addColumn("Tunjangan");
        a.addColumn("Upah_lembur");
        a.addColumn("Pajak");
        a.addColumn("Gaji_bersih");
        
        tabeldata.setModel(a);
        try {
            Statement stat = conec.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            while(rs.next()){
                a.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(10)});
                        System.out.println("Tabel Sukses");
            }
            }catch (Exception e) {
                    System.out.println("Tabel Gagal");
                    
                    
            
            }
            
    }

}


