/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu4b;

import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author naufal
 */
public class formpegawai extends javax.swing.JFrame {
    private Connection konek;

    /**
     * Creates new form formpegawai
     */
    public formpegawai() {
        initComponents();
        koneksidatabase();
        tabel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        a = new javax.swing.JLabel();
        kelamin = new javax.swing.JComboBox();
        status = new javax.swing.JComboBox();
        id_pegawai = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        masa_kerja = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Data Pegawai");

        jLabel2.setText("Id Pegawai");

        jLabel10.setText("Nama");

        jLabel11.setText("Status");

        jLabel14.setText("Masa Kerja");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        a.setText("Jenis Kelamin");

        kelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----", "Laki-Laki", "Perempuan", " " }));

        status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----", "Belum Menikah", "Menikah" }));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_Pegawai", "Nama", "Jenis Kelamin", "Status", "Alamat", "Masa Kerja"
            }
        ));
        jScrollPane2.setViewportView(tabeldata);

        jLabel3.setText("Alamat");

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(205, 205, 205))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masa_kerja, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(masa_kerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String vid_pegawai       =id_pegawai.getText();
       String vnama             =nama.getText();
       String vjenis_kelamin= (String) kelamin.getSelectedItem();
       String vstatus= (String)  status.getSelectedItem();
       String valamat=            alamat.getText();
       String vmasa_kerja=       masa_kerja.getText();

         if(id_pegawai.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Data masih kosong","PERHATIAN!",JOptionPane.WARNING_MESSAGE);
         }
        else {
            try {
                java.sql.Statement stat=konek.createStatement();
                ResultSet data=stat.executeQuery("SELECT * FROM tbl_pegawai WHERE nama='"+nama.getText()+"'");
             String sql="INSERT INTO tbl_pegawai VALUES ('"+vid_pegawai+"','"+vnama+"','"+vjenis_kelamin+"','"+vstatus+"','"+valamat+"','"+vmasa_kerja+"')";
             stat.executeUpdate(sql);
             stat.close();
             tabel();
              }
            catch (Exception exc) {
                System.err.println("Terjadi Kesalahan:"+exc);
    }                                      
         }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            String sql="update tbl_pegawai set nama='"+nama.getText()+
                    "',jenis_kelamin='"+kelamin.getSelectedItem()+
                    "',status='"+status.getSelectedItem()+
                    "',alamat='"+alamat.getText()+
                    "',masa_kerja='"+masa_kerja.getText()+
                    "'where id_pegawai='"+id_pegawai.getText().trim()+"'";
                if(id_pegawai.getText().trim().equals("")){
               JOptionPane.showMessageDialog(null,"Data Masih Kosong !","Edit Data",JOptionPane.WARNING_MESSAGE);
               id_pegawai.requestFocus();
                }
                else{
                    try{
                        Statement stat=konek.createStatement();
                        stat.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null,"Data Sudah Di Edit","Edit Data",JOptionPane.WARNING_MESSAGE);
                        stat.close();
                        //konek.close();
                        id_pegawai.requestFocus();
                        tabel();
                    }
                    catch(Exception exc){
                        System.err.println("Error:"+exc);
                    }
                
    }          
                                     
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String sql="select * from tbl_pegawai WHERE id_pegawai='"+id_pegawai.getText()+"'";
       try { 
           Statement stat=konek.createStatement(); {
            ResultSet rs=stat.executeQuery(sql);
            if(rs.next()){
                nama.setText(rs.getString(2)); 
                kelamin.setSelectedItem(rs.getString(3));
                status.setSelectedItem(rs.getString(4));
                alamat.setText(rs.getString(5));
                masa_kerja.setText(rs.getString(6));
            }
            
            else { JOptionPane.showMessageDialog(null,"Id Pegawai tidak ada","PERHATIAN",JOptionPane.WARNING_MESSAGE);
            id_pegawai.requestFocus();
            }
            tabel();
           }
       }
                 catch(Exception exc) {
                  System.err.println("Terjadi Kesalahan:"+exc);
                 }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    id_pegawai.setText("");
    nama.setText("");
    kelamin.setSelectedIndex(0);
    status.setSelectedIndex(0);
    alamat.setText(""); 
    masa_kerja.setText("");  
    id_pegawai.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String sql="delete from tbl_pegawai where id_pegawai='"+id_pegawai.getText().trim()+"'";
        if(id_pegawai.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(null,"Id Pagawai Masih Kosong !","Hapus Data",JOptionPane.WARNING_MESSAGE);
        id_pegawai.requestFocus();}
       
            else {
                try {
        Statement stat=(Statement) konek.createStatement();
        stat.executeUpdate(sql);
        JOptionPane.showMessageDialog(null,"Data Sudah Dihapus","Hapus Data",JOptionPane.WARNING_MESSAGE);
              
                stat.close();
                tabel();
                id_pegawai.setText("");
                nama.setText("");
                kelamin.setSelectedItem("-----");
                status.setSelectedItem("-----");
                alamat.setText(""); 
                masa_kerja.setText("");
                id_pegawai.requestFocus();      
    }                                     
catch(Exception exc){
        System.err.println(sql);
        System.err.println("Error:"+exc);
               
    }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formpegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formpegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formpegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formpegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formpegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JTextField alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField id_pegawai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox kelamin;
    private javax.swing.JTextField masa_kerja;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox status;
    private javax.swing.JTable tabeldata;
    // End of variables declaration//GEN-END:variables

    private void koneksidatabase() {
      try {
        Class.forName("com.mysql.jdbc.diver");
}
      catch (ClassNotFoundException cnf){}
try{konek=DriverManager.getConnection("jdbc:mysql://localhost/data_pegawai","root","");
    System.out.println("Koneksi Sukses");
}
catch (SQLException se) {
System.out.println("Koneksi Gagal"+se);
}
catch (Exception e){}   
    }

    private void tabel() {
         
        String sql ="SELECT * FROM tbl_pegawai";
        DefaultTableModel a = new DefaultTableModel ();
        a.addColumn("id_pegawai");
        a.addColumn("Nama");
        a.addColumn("Jenis Kelamin");
        a.addColumn("Status");
        a.addColumn("Alamat");
        a.addColumn("Masa Kerja");
       
        
        tabeldata.setModel(a);
        try {
            Statement stat = konek.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            while(rs.next()){
                a.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)});
                        System.out.println("Tabel Sukses");
            }
            }catch (Exception e) {
                    System.out.println("Tabel Gagal");
                    
    }
    }
}